imports:
    - { resource: packages/api_platform.yaml }
    - { resource: packages/cache.yaml }
    - { resource: packages/debug.yaml }
    - { resource: packages/doctrine.yaml }
    - { resource: packages/framework.yaml }
    - { resource: packages/messenger.yaml }
    - { resource: packages/monolog.yaml }
    - { resource: packages/prestashop.yaml }
    - { resource: packages/routing.yaml }
    - { resource: packages/translation.yaml }
    - { resource: packages/twig.yaml }
    - { resource: packages/ux_icons.yaml }
    - { resource: packages/validator.yaml }
    - { resource: packages/web_profiler.yaml }
    - { resource: services.yaml }
    - { resource: set_parameters.php }
    - { resource: addons/*.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(PS_THEME_NAME): "classic"
    translator.class: PrestaShopBundle\Translation\Translator
    translator.data_collector: PrestaShopBundle\Translation\DataCollectorTranslator
    prestashop_views: "%kernel.project_dir%/src/PrestaShopBundle/Resources/views"
    admin_page: "%prestashop_views%/Admin"
    env(PS_LOG_OUTPUT): "%kernel.logs_dir%/%kernel.environment%.log"
    env(PS_LOG_MAX_FILES): '30'
    env(PS_TRUSTED_PROXIES): ''
    mail_themes_uri: "/mails/themes"
    mail_themes_dir: "%kernel.project_dir%%mail_themes_uri%"
    modules_translation_paths: [ ]
    prestashop.controllers_all_shop_context:
        - AdminAccess
        - AdminFeatureFlag
        - AdminLanguages
        - AdminProfiles
        - AdminSpecificPriceRule
        - AdminStatuses
        - AdminSecurity
        - AdminSecuritySessionEmployee
        - AdminSecuritySessionCustomer
        - AdminTranslations

when@test:
    parameters:
        resources_dir: "%kernel.project_dir%/tests/Resources"
        test_translations_dir: "%resources_dir%/translations"
        translations_theme_dir: "%resources_dir%/themes"
        translations_modules_dir: "%resources_dir%/modules"
        prestashop.security.voter.product.class: Tests\Integration\Utility\PageVoter
