# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%secret%"
    annotations: true
    http_method_override: true
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # proxies configuration, see https://symfony.com/doc/current/deployment/proxies.html
    trusted_proxies: '%env(PS_TRUSTED_PROXIES)%'

    assets:
        version: !php/const PrestaShop\PrestaShop\Core\Version::VERSION
        packages:
            front_js:
                base_path: '../js'

when@test:
    framework:
        test: ~
        session:
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false
        trusted_proxies: 'REMOTE_ADDR'
