twig:
    file_name_pattern: '*.twig'
    autoescape: "name"
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: null
    form_themes:
        - '@PrestaShop/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig'
    paths:
        '%admin_page%/TwigTemplateForm': Twig
        '%admin_page%/Common': Common
        '%admin_page%/Configure/AdvancedParameters': AdvancedParameters
        '%admin_page%/Configure/ShopParameters': ShopParameters
        '%kernel.project_dir%/modules': Modules
        '%mail_themes_dir%': MailThemes
        '%prestashop_views%': PrestaShopCore
        '%prestashop.admin_dir%/themes/new-theme': AdminNewTheme
    globals:
        ps: '@PrestaShopBundle\Twig\Layout\PrestaShopLayoutGlobalVariables'
        webpack_server: false
        multistore_field_prefix: !php/const PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler::MULTISTORE_FIELD_PREFIX
        modify_all_shops_prefix: !php/const PrestaShopBundle\Form\Extension\ModifyAllShopsExtension::MODIFY_ALL_SHOPS_PREFIX
        disabling_switch_prefix: !php/const PrestaShopBundle\Form\Extension\DisablingSwitchExtension::FIELD_PREFIX

when@test:
    twig:
        strict_variables: true
